Demo\Model\Post:
    type: entity
    repositoryClass: Demo\Repository\PostRepository
    table: post
    id:
        id:
            type: integer
            generator: { strategy: auto }
    fields:
        title:
            type: string
            length: 255
        body:
            type: text
        created:
            type: datetime
        updated:
            type: datetime
