services:
    demo.blog.index:
        class: Demo\Controller\Blog\IndexController
        arguments:
            - '@demo.repository.post'
            - '@automapper_plus.mapper'
            - '@templating'
