services:
    demo.blog.index:
        class: Demo\Controller\Blog\IndexController
        arguments:
            - '@demo.repository.post'
            - '@automapper_plus.mapper'
            - '@templating'

    demo.blog.create:
        class: Demo\Controller\Blog\CreatePostController
        arguments:
            - '@demo.form.create_post'
            - '@templating'
            - '@automapper_plus.mapper'
            - '@demo.repository.post'

    demo.blog.edit:
        class: Demo\Controller\Blog\EditPostController
        arguments:
            - '@demo.form.edit_post'
            - '@templating'
            - '@automapper_plus.mapper'
            - '@demo.repository.post'
