services:
    demo.form.create_post:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', create]
        arguments:
            - 'Demo\Form\CreatePostType'

    demo.form.edit_post:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', create]
        arguments:
            - 'Demo\Form\EditPostType'
