demo.blog.index:
    path:       '/'
    defaults:
        _controller: demo.blog.index

demo.blog.create:
    path:       '/new'
    defaults:
        _controller: demo.blog.create

demo.blog.edit:
    path:       '/{id}/edit'
    defaults:
        _controller: demo.blog.edit

demo.blog.view:
    path:       '/{id}'
    defaults:
        _controller: demo.blog.view
